// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options, urlSearchParamsBodySerializer } from '@hey-api/client-axios';
import type { LoginAccessTokenApiLoginAccessTokenPostData, LoginAccessTokenApiLoginAccessTokenPostError, LoginAccessTokenApiLoginAccessTokenPostResponse, GetOrganizationApiEmployeeOrganizationGetError, GetOrganizationApiEmployeeOrganizationGetResponse, CreateOrganizationApiEmployeeOrganizationPostData, CreateOrganizationApiEmployeeOrganizationPostError, CreateOrganizationApiEmployeeOrganizationPostResponse, GetEmployeeApiEmployeeEmployeeIdGetData, GetEmployeeApiEmployeeEmployeeIdGetError, GetEmployeeApiEmployeeEmployeeIdGetResponse, GetEmployeesByOrganizationApiEmployeeOrganizationOrganizationIdGetData, GetEmployeesByOrganizationApiEmployeeOrganizationOrganizationIdGetError, GetEmployeesByOrganizationApiEmployeeOrganizationOrganizationIdGetResponse, CreateEmployeeApiEmployeePostData, CreateEmployeeApiEmployeePostError, CreateEmployeeApiEmployeePostResponse, DeleteEmployeeApiEmployeeDeleteData, DeleteEmployeeApiEmployeeDeleteError, DeleteEmployeeApiEmployeeDeleteResponse, GetTotalTipsApiTipsTipsGetError, GetTotalTipsApiTipsTipsGetResponse, AddTipApiTipsAddTipPostData, AddTipApiTipsAddTipPostError, AddTipApiTipsAddTipPostResponse } from './types.gen';

/**
 * Login Access Token
 */
export const loginAccessTokenApiLoginAccessTokenPost = (options: Options<LoginAccessTokenApiLoginAccessTokenPostData>) => { return (options?.client ?? client).post<LoginAccessTokenApiLoginAccessTokenPostResponse, LoginAccessTokenApiLoginAccessTokenPostError>({
    ...options,
    ...urlSearchParamsBodySerializer,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
    },
    url: '/api/login/access-token'
}); };

/**
 * Get Organization
 */
export const getOrganizationApiEmployeeOrganizationGet = (options?: Options) => { return (options?.client ?? client).get<GetOrganizationApiEmployeeOrganizationGetResponse, GetOrganizationApiEmployeeOrganizationGetError>({
    ...options,
    url: '/api/employee/organization'
}); };

/**
 * Create Organization
 */
export const createOrganizationApiEmployeeOrganizationPost = (options: Options<CreateOrganizationApiEmployeeOrganizationPostData>) => { return (options?.client ?? client).post<CreateOrganizationApiEmployeeOrganizationPostResponse, CreateOrganizationApiEmployeeOrganizationPostError>({
    ...options,
    url: '/api/employee/organization'
}); };

/**
 * Get Employee
 */
export const getEmployeeApiEmployeeEmployeeIdGet = (options: Options<GetEmployeeApiEmployeeEmployeeIdGetData>) => { return (options?.client ?? client).get<GetEmployeeApiEmployeeEmployeeIdGetResponse, GetEmployeeApiEmployeeEmployeeIdGetError>({
    ...options,
    url: '/api/employee/{employee_id}'
}); };

/**
 * Get Employees By Organization
 */
export const getEmployeesByOrganizationApiEmployeeOrganizationOrganizationIdGet = (options: Options<GetEmployeesByOrganizationApiEmployeeOrganizationOrganizationIdGetData>) => { return (options?.client ?? client).get<GetEmployeesByOrganizationApiEmployeeOrganizationOrganizationIdGetResponse, GetEmployeesByOrganizationApiEmployeeOrganizationOrganizationIdGetError>({
    ...options,
    url: '/api/employee/organization/{organization_id}'
}); };

/**
 * Create Employee
 */
export const createEmployeeApiEmployeePost = (options: Options<CreateEmployeeApiEmployeePostData>) => { return (options?.client ?? client).post<CreateEmployeeApiEmployeePostResponse, CreateEmployeeApiEmployeePostError>({
    ...options,
    url: '/api/employee/'
}); };

/**
 * Delete Employee
 */
export const deleteEmployeeApiEmployeeDelete = (options: Options<DeleteEmployeeApiEmployeeDeleteData>) => { return (options?.client ?? client).delete<DeleteEmployeeApiEmployeeDeleteResponse, DeleteEmployeeApiEmployeeDeleteError>({
    ...options,
    url: '/api/employee/'
}); };

/**
 * Get Total Tips
 */
export const getTotalTipsApiTipsTipsGet = (options?: Options) => { return (options?.client ?? client).get<GetTotalTipsApiTipsTipsGetResponse, GetTotalTipsApiTipsTipsGetError>({
    ...options,
    url: '/api/tips/tips'
}); };

/**
 * Add Tip
 */
export const addTipApiTipsAddTipPost = (options: Options<AddTipApiTipsAddTipPostData>) => { return (options?.client ?? client).post<AddTipApiTipsAddTipPostResponse, AddTipApiTipsAddTipPostError>({
    ...options,
    url: '/api/tips/add_tip'
}); };