// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_access_token_api_login_access_token_post = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type Employee = {
    name: string;
    is_active?: boolean;
    upi_id: string;
    employee_id?: string;
    org_id: string;
};

export type EmployeeCreate = {
    name: string;
    is_active?: boolean;
    upi_id: string;
    organization_id: string;
};

export type EmployerOrganization = {
    email: string;
    organization_name: string;
    organization_description: string;
    is_active?: boolean;
    organization_id?: string;
    hashed_password: string;
    total_tips?: number;
};

export type EmployerOrganizationCreate = {
    email: string;
    organization_name: string;
    organization_description: string;
    is_active?: boolean;
    password: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type OrganizationEmployees = {
    org_id: string;
    organization_name: string;
    organization_description: string;
    data: Array<Employee>;
};

export type TipCreate = {
    employee_id: string;
    amount: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginAccessTokenApiLoginAccessTokenPostData = {
    body: Body_login_access_token_api_login_access_token_post;
};

export type LoginAccessTokenApiLoginAccessTokenPostResponse = Token;

export type LoginAccessTokenApiLoginAccessTokenPostError = HTTPValidationError;

export type GetOrganizationApiEmployeeOrganizationGetResponse = EmployerOrganization;

export type GetOrganizationApiEmployeeOrganizationGetError = unknown;

export type CreateOrganizationApiEmployeeOrganizationPostData = {
    body: EmployerOrganizationCreate;
};

export type CreateOrganizationApiEmployeeOrganizationPostResponse = EmployerOrganization;

export type CreateOrganizationApiEmployeeOrganizationPostError = HTTPValidationError;

export type GetEmployeeApiEmployeeEmployeeIdGetData = {
    path: {
        employee_id: string;
    };
};

export type GetEmployeeApiEmployeeEmployeeIdGetResponse = Employee;

export type GetEmployeeApiEmployeeEmployeeIdGetError = HTTPValidationError;

export type GetEmployeesByOrganizationApiEmployeeOrganizationOrganizationIdGetData = {
    path: {
        organization_id: string;
    };
};

export type GetEmployeesByOrganizationApiEmployeeOrganizationOrganizationIdGetResponse = OrganizationEmployees;

export type GetEmployeesByOrganizationApiEmployeeOrganizationOrganizationIdGetError = HTTPValidationError;

export type CreateEmployeeApiEmployeePostData = {
    body: EmployeeCreate;
};

export type CreateEmployeeApiEmployeePostResponse = unknown;

export type CreateEmployeeApiEmployeePostError = HTTPValidationError;

export type DeleteEmployeeApiEmployeeDeleteData = {
    query: {
        employee_id: string;
    };
};

export type DeleteEmployeeApiEmployeeDeleteResponse = unknown;

export type DeleteEmployeeApiEmployeeDeleteError = HTTPValidationError;

export type GetTotalTipsApiTipsTipsGetResponse = unknown;

export type GetTotalTipsApiTipsTipsGetError = unknown;

export type AddTipApiTipsAddTipPostData = {
    body: TipCreate;
};

export type AddTipApiTipsAddTipPostResponse = unknown;

export type AddTipApiTipsAddTipPostError = HTTPValidationError;

export type $OpenApiTs = {
    '/api/login/access-token': {
        post: {
            req: LoginAccessTokenApiLoginAccessTokenPostData;
            res: {
                /**
                 * Successful Response
                 */
                '200': Token;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/employee/organization': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                '200': EmployerOrganization;
            };
        };
        post: {
            req: CreateOrganizationApiEmployeeOrganizationPostData;
            res: {
                /**
                 * Successful Response
                 */
                '200': EmployerOrganization;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/employee/{employee_id}': {
        get: {
            req: GetEmployeeApiEmployeeEmployeeIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                '200': Employee;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/employee/organization/{organization_id}': {
        get: {
            req: GetEmployeesByOrganizationApiEmployeeOrganizationOrganizationIdGetData;
            res: {
                /**
                 * Successful Response
                 */
                '200': OrganizationEmployees;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/employee/': {
        post: {
            req: CreateEmployeeApiEmployeePostData;
            res: {
                /**
                 * Successful Response
                 */
                '200': unknown;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
        delete: {
            req: DeleteEmployeeApiEmployeeDeleteData;
            res: {
                /**
                 * Successful Response
                 */
                '200': unknown;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
    '/api/tips/tips': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                '200': unknown;
            };
        };
    };
    '/api/tips/add_tip': {
        post: {
            req: AddTipApiTipsAddTipPostData;
            res: {
                /**
                 * Successful Response
                 */
                '200': unknown;
                /**
                 * Validation Error
                 */
                '422': HTTPValidationError;
            };
        };
    };
};